def hello_from_bin() -> str: ...
def read_file(path: str, sheet: str, address: str) -> str: ...
class Book:
    path: str

    def __init__(self, path: str) -> None: ...
    def __repr__(self) -> str: ...
    def get_value(self, sheet: str, address: str) -> str: ...
